export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const LOG_IN_ERROR = "LOG_IN_ERROR";
export const UPDATE_FRIENDS = 'UPDATE_FRIENDS';

export const GET_USERS = 'GET_USERS';
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const EDIT_USERS_ERROR = "EDIT_USERS_ERROR";
export const UPDATE_ACTIVE_USER = "UPDATE_ACTIVE_USER";

export const SET_LOADING = "SET_LOADING";

export const CREATE_AGREEMENT = "CREATE_AGREEMENT";
export const EDIT_AGREEMENT = "EDIT_AGREEMENT";
export const DELETE_AGREEMENT = "DELETE_AGREEMENT";
export const GET_AGREEMENT = "GET_AGREEMENT";
export const AGREEMENT_ERROR = "AGREEMENT_ERROR";
export const RESET_ACTIVE_AGREEMENT = "RESET_ACTIVE_AGREEMENT";
export const NEW_SEARCH = "NEW_SEARCH";